In [1]:
import pandas as pd
import numpy as np

In [2]:
movie=pd.read_csv(r"C:\\Users\\acrer\\Downloads\\movie\\tmdb_5000_movies.csv")
credit=pd.read_csv(r"C:\\Users\\acrer\\Downloads\\movie\\tmdb_5000_credits.csv")

In [3]:
print(movie.shape)

(4803, 20)

In [4]:
print(credit.shape)

(4803, 4)

In [5]:
df=movie.merge(credit,on='title')
df.shape

(4809, 23)

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   str
 2   homepage              1713 non-null   str
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   str
 5   original_language     4809 non-null   str
 6   original_title        4809 non-null   str
 7   overview              4806 non-null   str
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   str
 10  production_countries  4809 non-null   str
 11  release_date          4808 non-null   str
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   str
 15  status                4809 non-null   str
 16  tagline               3965 non-null   str
 17  title                 4809 non-null   str
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   str
 22  crew                  4809 non-null   str
dtypes: float64(3), int64(5), str(15)
memory usage: 39.1 MB

In [7]:
# fetching the columns we need
df=df[['movie_id','title','overview','genres','keywords','cast','crew']]
df.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [8]:
df.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [9]:
df.dropna(inplace=True)

In [10]:
df.duplicated().sum()

np.int64(0)

In [ ]:
#convert string representation of a list into list
import ast
def convert1(obj):
    L=[]
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L
df['genres']=df['genres'].apply(convert1)

In [ ]:
df.iloc[0].genres

['Action', 'Adventure', 'Fantasy', 'Science Fiction']

In [14]:
#convert dictionary into a list
df['keywords']=df['keywords'].apply(convert1)

In [15]:
#convert dictionary into list and get only top 3 actors name
def convert2(obj):
    L=[]
    counter=0
    for i in ast.literal_eval(obj):
        if counter!=3:
          L.append(i['name'])
          counter+=1
        else:
           break  
    return L
df['cast']=df['cast'].apply(convert2)

In [16]:
# to find director (where job=director)
def convert3(obj):
    L=[]
    for i in ast.literal_eval(obj):
        if i['job']=='Director':
            L.append(i['name'])
            break
    return L
df['crew']=df['crew'].apply(convert3)

In [17]:
df.head(3)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]

In [17]:
#if overview contains missing value replace it with empty string
df['overview'] = df['overview'].fillna('')
print(df['overview'].apply(type).value_counts())

overview
<class 'str'>    4806
Name: count, dtype: int64

In [18]:
#if value in overview is a string then split if not then use[]
df['overview'] = df['overview'].apply(
    lambda x: x.split() if isinstance(x, str) else []
)

In [19]:
print(type(df['overview'].iloc[0]))

<class 'list'>

In [ ]:
#removing space between words
df['genres']=df['genres'].apply(lambda x:[i.replace(" ","")for i in x])
df['keywords']=df['keywords'].apply(lambda x:[i.replace(" ","")for i in x])
df['cast']=df['cast'].apply(lambda x:[i.replace(" ","")for i in x])
df['crew']=df['crew'].apply(lambda x:[i.replace(" ","")for i in x])

In [ ]:
cols = ['overview', 'genres', 'keywords', 'cast', 'crew']
for col in cols:
    print("\n", col)
    print(df[col].apply(type).value_counts())

 overview
overview
<class 'list'>    4806
Name: count, dtype: int64

 genre
genre
<class 'list'>    4806
Name: count, dtype: int64

 keywords
keywords
<class 'list'>    4806
Name: count, dtype: int64

 cast
cast
<class 'list'>    4806
Name: count, dtype: int64

 crew
crew
<class 'list'>    4806
Name: count, dtype: int64

In [ ]:
df['tags']=df['overview']+df['genres']+df['keywords']+df['cast']+df['crew']
new_df=df[['movie_id','title','genres','tags']]
new_df.head()

,movie_id,title,genre,tags
0,19995,Avatar,"[Action, Adventure, Fantasy, ScienceFiction]","[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[Action, Adventure, Crime]","[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[Action, Adventure, ScienceFiction]","[John, Carter, is, a, war-weary,, former, mili..."

In [25]:
#join every list in space
new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))
new_df.head()

,movie_id,title,genre,tags
0,19995,Avatar,"[Action, Adventure, Fantasy, ScienceFiction]","In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,"[Action, Adventure, Crime]",A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]",Following the death of District Attorney Harve...
4,49529,John Carter,"[Action, Adventure, ScienceFiction]","John Carter is a war-weary, former military ca..."

In [26]:
new_df['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver JamesCameron'

In [27]:
#fetch max times coming word in any movie in the column tag except stop words (is,are,the,in,and)
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=3000,stop_words='english')

In [28]:
vectors=cv.fit_transform(new_df['tags']).toarray()

In [29]:
print(cv.get_feature_names_out())

['000' '10' '11' ... 'zombies' 'zoo' 'zooeydeschanel']

In [30]:
#python library used for natural language processing,text analysis.Here we used this for stemming.
import nltk
from nltk.stem.porter import PorterStemmer # for standard english text preprocessing
ps=PorterStemmer()

In [31]:
#ps.stem('Dancing') will give output Danc(root word)
def stem(text):
    y=[]
    for i in text.split():
        y.append(ps.stem(i))

    return " ".join(y)

In [32]:
new_df['tags']=new_df['tags'].apply(stem)

In [33]:
#fetch max times coming word in any movie in the column tag except stop words (is,are,the,in,and)
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=3000,stop_words='english')

In [34]:
#creating vectors from column tags and converting them to an array
vectors=cv.fit_transform(new_df['tags']).toarray()

In [35]:
print(cv.get_feature_names_out())

['000' '10' '11' ... 'zombi' 'zoo' 'zooeydeschanel']

In [36]:
#how closely two vectors align in direction(angle between two movies)
from sklearn.metrics.pairwise import cosine_similarity
cs=cosine_similarity(vectors)
cs.shape

(4806, 4806)

In [37]:
cs[0]

array([1.        , 0.09416472, 0.09416472, ..., 0.04984448, 0.        ,
       0.        ], shape=(4806,))

In [38]:
# will give similarity with movie index in sorted order
sorted(list(enumerate(cs[0])),reverse = True,key=lambda x:x[1])[1:11]

[(1214, np.float64(0.32200409305581884)),
 (3728, np.float64(0.3162277660168379)),
 (507, np.float64(0.2927700218845599)),
 (61, np.float64(0.2788866755113585)),
 (539, np.float64(0.2732295333235123)),
 (582, np.float64(0.26561990862896234)),
 (2405, np.float64(0.26082026547865056)),
 (1916, np.float64(0.2571428571428571)),
 (1192, np.float64(0.25226248955475644)),
 (1202, np.float64(0.2467838236981868))]

In [39]:
#function to recommend movie for given input (movie)
def recommend(movie):
    index = new_df[new_df['title']==movie].index[0]
    dist=cs[index]
    movie_list=sorted(list(enumerate(dist)),reverse = True,key=lambda x:x[1])[1:11]

    for i in movie_list:
        print(new_df.iloc[i[0]].title)

In [40]:
recommend('Batman Begins')

The Dark Knight
Batman
Batman
10th & Wolf
Amidst the Devil's Wings
Synecdoche, New York
Batman v Superman: Dawn of Justice
Rockaway
The Dark Knight Rises
Defendor

In [41]:
import pickle

pickle.dump(new_df, open('movie_list.pkl', 'wb'))
pickle.dump(cs, open('similarity.pkl', 'wb'))